version: '3'
services: 
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        env_file: 
            - db.env
        volumes: 
            - ./tmp/db:/var/lib/postgressql/data
        restart: 
            always
    app:
        build: .
        ports: 
            - "3000:3000"
        env_file: 
            - app.env 
        volumes: 
            - .:/app
        command: > 
            sh -c "rm -f /app/tmp/pids/server.pid
            && bundle install 
            && rails db:create
            && rails db:migrate
            && rails s -p 3000 -b 0.0.0.0"
        depends_on: 
            - db
        restart: 
            always
